import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#414141',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFD700',
    marginBottom: 20,
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#014991',
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFD700',
    marginBottom: 20,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 18,
  },
  card: {
    flexDirection: 'row',
    backgroundColor: '#1e1e1e',
    padding: 10,
    marginVertical: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#FFD700',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    width: 350,
    alignSelf: 'center',
  },
  cardImageSmall: {
    width: 80,
    height: 80,
    borderRadius: 10,
    marginRight: 15,
  },
  cardInfo: {
    justifyContent: 'center',
  },
  cardName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFD700',
  },
  cardDetail: {
    fontSize: 16,
    color: '#fff',
    marginTop: 2,
  },

  detailContainer: {
    flex: 1,
    backgroundColor: '#2c2c2c',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  detailTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFD700',
    marginBottom: 20,
    textAlign: 'center',
  },
  detailCard: {
    backgroundColor: '#1e1e1e',
    padding: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#FFD700',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    alignItems: 'center',
    width: '20%',
  },
  cardImageLarge: {
    width: 180,
    height: 180,
    borderRadius: 15,
    marginBottom: 15,
  },
  detailText: {
    fontSize: 20,
    color: '#fff',
    marginTop: 5,
    fontWeight: 'bold',
  },
});

export default styles;